datasets:
  data_dir: 'data/synthetic'
  context: 'therapy'
  therapy_source_dir: 'data/source/HOPE_WSDM_2022/conversations'
  legal_source_dir: 'data/source/legal'
  persona_file: 'data/source/Persona_Hub_200000.jsonl'
models:
  llm_model: 'gpt-4o'  # 'gpt-4-turbo', 'gpt-4o'
inference:
  verbose: False
  print_every: 50
  num_personas: 1
  num_samples_per_context: 1
  output_dir: 'data/output/'
  save_output_response: True
  output_file_name: 'conversation'